SHOW USER

-- TABLES ----------------------------------------------------------------------


-- Persona
CREATE TABLE Persona(
    --id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id NUMBER NOT NULL,
    nombre VARCHAR(127),
    apellidoPaterno VARCHAR(127),
    apellidoMaterno VARCHAR(127),
    fechaDeInicio DATE,
    fechaDeFin DATE,
    PRIMARY KEY(id)
)
-- DROP TABLE Persona;


-- PlanDeEstudio
CREATE TABLE PlanDeEstudio(
    --id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id NUMBER NOT NULL,
    idDeCarrera CHAR(15),  -- FK
    nombre VARCHAR(127),
    fechaDeAutorizacion DATE,
    PRIMARY KEY(id)
)
-- DROP TABLE PlanDeEstudio;


-- Alumno
CREATE TABLE Alumno(
    idDePersona NUMBER NOT NULL UNIQUE,
    idDePlanDeEstudio NUMBER,
    FOREIGN KEY(idDePersona) REFERENCES Persona(id),
    FOREIGN KEY(idDePlanDeEstudio) REFERENCES PlanDeEstudio(id)
)
-- DROP TABLE Alumno;


-- Titulo
CREATE TABLE Titulo(
    --id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id NUMBER NOT NULL UNIQUE,
    nombre VARCHAR(63),
    PRIMARY KEY (id)
)
-- DROP TABLE Titulo;


-- Profesor
CREATE TABLE Profesor(
    idDePersona NUMBER NOT NULL UNIQUE,
    idDeTitulo NUMBER,
    FOREIGN KEY(idDePersona) REFERENCES Persona(id),
    FOREIGN KEY(idDeTitulo) REFERENCES Titulo(id)
)
-- DROP TABLE Profesor;



-- TEST DATA -------------------------------------------------------------------
INSERT INTO Persona VALUES(1, 'Juan', 'Perez', 'Gonzalez', '01-OCT-2010', '01-DEC-2015');
INSERT INTO Persona VALUES(2, 'Maria', 'Gonzalez', 'Perez', '01-OCT-2010', '01-DEC-2015');
INSERT INTO Persona VALUES(3, 'Pedro', 'Garcia', 'Garcia', '01-OCT-2010', '01-DEC-2015');
INSERT INTO Persona VALUES(4, 'Jose', 'Garcia', 'Garcia', '01-OCT-2010', '01-DEC-2015');

INSERT INTO PlanDeEstudio VALUES(1, 'ISC', 'Ingenieria en Sistemas Computacionales', '01-OCT-2010');
INSERT INTO PlanDeEstudio VALUES(2, 'ITI', 'Ingenieria en Tecnologias de la Informacion', '01-OCT-2010');
INSERT INTO PlanDeEstudio VALUES(3, 'ITC', 'Ingenieria en Tecnologias de la Comunicacion', '01-OCT-2010');

INSERT INTO Alumno VALUES(1, 100);




--? XD --------------------------------------------------------------------------
CREATE TABLE registro_tablas(
    idDePersona NUMBER NOT NULL,
    FOREIGN KEY(idDePersona) REFERENCES Persona(id),
)


-- PL/SQL ----------------------------------------------------------------------
-- Create an AUTOINCREMENT column funciton
CREATE OR REPLACE FUNCTION autoincrement_column(
        p_table_name IN VARCHAR2,
    p_column_name IN VARCHAR2
)
COMMIT